// Command fresco is a terminal screensaver for the fresco field engine: it fills
// the pane with a slow-drifting, palette-coloured generative field and animates
// it full-screen until you quit.
//
//	go install github.com/ZviBaratz/fresco/cmd/fresco@latest
//	fresco                       # cycle the whole roster, auto-sized
//	fresco --variant ripple      # pin one field
//	fresco --palette nord --fps 60
//	fresco --list                # list variants and palettes
//	fresco --once > frame.txt    # capture a single frame
//
// Keys (on a real terminal): q or Ctrl-C quit · space next variant · p pause.
//
// This is the impure shell around the pure fresco.Render engine: terminal size,
// the frame clock, signals, raw-mode keys, and stdout all live here and in the
// rest of cmd/fresco, never in the fresco package. main is the only place that
// calls os.Exit, and only after the interactive run has returned through its
// deferred terminal restore — so the terminal is put back on every exit path,
// including Ctrl-C and a panic.
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"os/signal"
	"runtime/debug"
	"strings"
	"syscall"

	"github.com/ZviBaratz/fresco"
	"github.com/charmbracelet/lipgloss"
	"github.com/muesli/termenv"
)

// version is the binary's build version. GoReleaser injects the release tag via
// -ldflags "-X main.version=..."; a plain `go build` leaves it "dev", and
// resolveVersion then falls back to the module version the Go toolchain embeds
// (so `go install ...@v1.2.0` still reports v1.2.0).
var version = "dev"

func main() {
	c := newOSConsole()

	cfg, err := resolveConfig(os.Args[1:], os.Getenv, c.IsTTY(), detectProfile())
	if err != nil {
		if errors.Is(err, flag.ErrHelp) {
			usage(os.Stdout)
			return // exit 0
		}
		if errors.Is(err, errVersion) {
			info, ok := debug.ReadBuildInfo()
			_, _ = fmt.Fprintln(os.Stdout, "fresco "+resolveVersion(version, info, ok))
			return // exit 0
		}
		fail(err)
		fmt.Fprintln(os.Stderr, "run 'fresco -h' for usage")
		os.Exit(2)
	}

	// SIGINT (non-raw Ctrl-C) and SIGTERM cancel the context; the interactive
	// loop returns through its deferred teardown. The handler never restores or
	// exits itself — that is what keeps the terminal from wedging on Ctrl-C.
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	if err := runApp(ctx, c, cfg); err != nil {
		fail(err)
		os.Exit(1)
	}
}

// resolveVersion chooses the most specific build version available: an
// ldflags-injected value wins; else the module version embedded by the Go
// toolchain (from `go install ...@version`); else it stays "dev". It is pure so
// the choice is unit-tested without a build.
func resolveVersion(ldflags string, info *debug.BuildInfo, ok bool) string {
	if ldflags != "" && ldflags != "dev" {
		return ldflags
	}
	if ok && info != nil && info.Main.Version != "" && info.Main.Version != "(devel)" {
		return info.Main.Version
	}
	return ldflags
}

// fail prints an error to stderr under a single "fresco:" prefix. Some errors
// already carry it (fresco.Palette.Validate namespaces its own), so it is not
// doubled.
func fail(err error) {
	msg := err.Error()
	if !strings.HasPrefix(msg, "fresco:") {
		msg = "fresco: " + msg
	}
	fmt.Fprintln(os.Stderr, msg)
}

// detectProfile probes the ambient terminal's colour depth once. resolveConfig
// folds this into a pinned profile so the animation loop never re-probes stdout
// (see resolveProfile). The lipgloss probe is the only impure part; the mapping
// is split out so it can be unit-tested.
func detectProfile() fresco.ColorProfile {
	return termenvToProfile(lipgloss.ColorProfile())
}

// termenvToProfile maps termenv's detected profile onto fresco's own enum.
func termenvToProfile(p termenv.Profile) fresco.ColorProfile {
	switch p {
	case termenv.TrueColor:
		return fresco.TrueColor
	case termenv.ANSI256:
		return fresco.ANSI256
	case termenv.ANSI:
		return fresco.ANSI16
	default: // termenv.Ascii
		return fresco.NoColor
	}
}

// usage prints the help text. It is hand-written rather than flag's autogenerated
// dump so the keys, environment, and examples sit alongside the flags.
func usage(w io.Writer) {
	_, _ = fmt.Fprint(w, `fresco — a generative terminal screensaver

Usage:
  fresco [flags]

Flags:
  --variant name          field to show: rain, tunnel, ripple, galaxy, aurora,
                          or cycle/all to rotate the roster (default cycle)
  --palette name|hex      a preset (tokyo-night, nord, gruvbox, mono) or five
                          comma-separated "#rrggbb" anchors (default tokyo-night)
  --fps n                 animation frames per second (default 30)
  --seconds-per-variant n how long each variant holds when cycling (default 6)
  --focal-row n           row the field emanates from; negative centres it (default -1)
  --lum-range f           override the density-vs-luminance split, in [0,1]
  --profile name          colour depth: auto, truecolor, ansi256, ansi16, nocolor
  --duration d            run for this long then exit, e.g. 30s (default: until quit)
  --size WxH              override auto-size, e.g. 100x30 (default: detect)
  --once                  render a single frame to stdout and exit
  --list                  list the variants and palettes, then exit
  --version               print the fresco version and exit

Keys (interactive, on a TTY):
  q, Ctrl-C  quit      space  next variant      p  pause

Environment:
  NO_COLOR      disable colour (honoured in --profile auto)
  FORCE_COLOR   force colour even when stdout is not a terminal

When stdout is not a terminal (a pipe, a redirect, CI), fresco renders one frame
and exits instead of animating.
`)
}
