blank_issues_enabled: true
contact_links:
  - name: Question or discussion
    url: https://github.com/ZviBaratz/fresco/discussions
    about: For open-ended questions and ideas, please start a discussion.
